services:
  nginx:
    image: nginx:latest
    ports:
      - "6080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - app_network

  app1:
    build: .
    environment:
      - INSTANCE_NUM=1
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6090/api/v1/contact"]
      interval: 10s
      timeout: 5s
      retries: 3

  app2:
    build: .
    environment:
      - INSTANCE_NUM=2
    networks:
      - app_network

  app3:
    build: .
    environment:
      - INSTANCE_NUM=3
    networks:
      - app_network

networks:
  app_network:
    driver: bridge